// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qitjnuytjdchfwyegdlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdGpudXl0amRjaGZ3eWVnZGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzMzMDksImV4cCI6MjA3MzEwOTMwOX0.idJcjoIdWXowGWsYWbwNX_2M8a2NxfSiLSQmE0Vi4IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});